name: Demo CI/CD
on:
  push:
    branches:
      - 'demo'
  pull_request:
    branches:
      - 'demo'
  workflow_dispatch:

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'action') || contains(github.event.pull_request.title, 'action') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm@10.12.1 only-allow
          pnpm install
          npx nx reset
          pnpm prisma:generate
          pnpm build:all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # aidlink Image
      - name: build && push aidlink
        id: build-push-aidlink
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.c2c
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: esatya/rahat-project-aidlink:demo
